version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/perfin/backend
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/backend
      - node/with-cache:
          steps:
            - run: ls
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test